### PR TITLE
Read only checks

### PR DESCRIPTION
**Pull request by JobLeonard**
This needs to be verified before merging into master. 

Even if I made no mistakes in adding these checks to loompy itself, there might be other code we use *relying* on loompy that accidentally modifies files where it did not intend to.

See issue #31

### CODE REVIEW

**Comment by JobLeonard** [comment]
@gioelelm, @slinnarsson, did you have time to test if this modification breaks anything unexpected?

In time we should probably come up with a set of extensive tests, but for now it would still help if you switche to the branch, build loompy from that version, and run a few test pipelines where you think something funny could happen. It should bring up obvious bugs first.

Also, is the build fail a bug in my code? It doesn't look related:
```
The command "make html" exited with 2.
0.00s$ cd ..
```

**Comment by slinnarsson** [comment]
Hi Job

Did you figure out why the checks fail? Should I merge this or not?

**Comment by JobLeonard** [comment]
Sorry, no, it had slipped my mind. I should take a look at it again

**Comment by JobLeonard** [comment]
I just remembered that this pull request also includes the unix timestamp thing. I'll prioritise it for that reason as well.

**Comment by gioelelm** [comment]
Check fail because sphinx people has made breaking changes. I suggest to change the travisCI yml to do pip install sphinx instead of installing from source.

Also make sure in your pull request line 45 of loompy/doc/_ext/edit_on_github.py sets is still set to the parameter to ".rst"

**Comment by JobLeonard** [comment]
I haven't changed any code except for pulling in the changes from the main branch. There probably are some changes that I need to take a closer look at again in case that broke something.

**Comment by JobLeonard** [comment]
These checks only deal with the documentation, right? Nothing that involves actual testing of the code?

**Comment by gioelelm** [comment]
exactly

**Comment by slinnarsson** [comment]
Closing this now, as most readonly checks have been added separately in the meantime

**Pull request closed without merging**
