### PR TITLE
Add compression support for row_attrs and col_attrs datasets.

### PR DESCRIPTION
**Pull request by ghuls**
Add compression support for row_attrs and col_attrs datasets
as this can reduce the filesize quite significantly.

### CODE REVIEW

**Comment by slinnarsson** [comment]
Thanks! This has been on my wish list for some time. I’ll take a look tomorrow and approve if all looks good.

**Comment by ghuls** [comment]
We generate quite a lot of big loom files with a lot of `row_attrs` and `col_attrs`.

Adding compression of row_attrs and col_attrs datasets reduces the filesize quite significantly.

```
# Original
Aerts_Fly_AdultBrain_Unfiltered_157k.loom	956M

# With gzip compression level (compression_opts=) set.
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip2.loom	586M (current compression level)
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip6.loom	426M
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip8.loom	422M


# Original
Zhang_Human_Brain_30k.loom	158M

# With gzip compression level (compression_opts=) set.
Zhang_Human_Brain_30k.gzip2.loom	120M (current compression level)


# Original
SCC_bbknn.SCENIC_SCope_output.loom	373M

# With gzip compression level (compression_opts=) set.
SCC_bbknn.SCENIC_SCope_output.gzip1.loom	251M
SCC_bbknn.SCENIC_SCope_output.gzip2.loom	241M (current compression level)
SCC_bbknn.SCENIC_SCope_output.gzip3.loom	232M
SCC_bbknn.SCENIC_SCope_output.gzip4.loom	209M
SCC_bbknn.SCENIC_SCope_output.gzip5.loom	202M
SCC_bbknn.SCENIC_SCope_output.gzip6.loom	195M
SCC_bbknn.SCENIC_SCope_output.gzip7.loom	194M
SCC_bbknn.SCENIC_SCope_output.gzip8.loom	190M
SCC_bbknn.SCENIC_SCope_output.gzip9.loom	187M
```

Below some results with the `h5repack` tool of the HDF5 toolkit to see the compression ratio:
```
# Elapsed wall time: 2:00.20 = 120.20 seconds
$ h5repack -v -f GZIP=2 SCC_bbknn.SCENIC_SCope_output.loom SCC_bbknn.SCENIC_SCope_output.h5repack.gzip2.loom

No all objects to modify layout
All objects to apply filter are...
 All with GZIP, parameter 2
Making new file ...
-----------------------------------------
 Type     Filter (Compression)     Name
-----------------------------------------
 group                       /
  attr                        last_modified
 group                       /attrs
 dset       (1.000:1)        /attrs/CreationDate
 dset       (1.000:1)        /attrs/LOOM_SPEC_VERSION
 dset       (1.000:1)        /attrs/MetaData
 group                       /col_attrs
  attr                        last_modified
 dset     GZIP   (5.760:1)   /col_attrs/CellID
  attr                        last_modified
 dset     GZIP   (8.140:1)   /col_attrs/ClusterID
  attr                        last_modified
 dset     GZIP   (9.799:1)   /col_attrs/Clusterings
  attr                        last_modified
 dset     GZIP   (1.090:1)   /col_attrs/Embedding
  attr                        last_modified
 dset     GZIP   (1.072:1)   /col_attrs/Embeddings_X
  attr                        last_modified
 dset     GZIP   (1.078:1)   /col_attrs/Embeddings_Y
  attr                        last_modified
 dset     GZIP   (1.347:1)   /col_attrs/MotifRegulonsAUC
  attr                        last_modified
 dset     GZIP   (1.447:1)   /col_attrs/TrackRegulonsAUC
  attr                        last_modified
 dset     GZIP   (8.392:1)   /col_attrs/batch
  attr                        last_modified
 dset     GZIP   (8.395:1)   /col_attrs/louvain
  attr                        last_modified
 dset     GZIP   (1.500:1)   /col_attrs/n_counts
  attr                        last_modified
 dset     GZIP   (3.270:1)   /col_attrs/n_genes
  attr                        last_modified
 dset     GZIP   (1.142:1)   /col_attrs/percent_mito
  attr                        last_modified
 group                       /col_graphs
 group                       /layers
 dset     GZIP   (1.000:1)   /matrix
 group                       /row_attrs
  attr                        last_modified
 dset     GZIP   (56.518:1)  /row_attrs/ClusterMarkers_0
  attr                        last_modified
 dset     GZIP   (22.380:1)  /row_attrs/ClusterMarkers_0_avg_logFC
  attr                        last_modified
 dset     GZIP   (60.734:1)  /row_attrs/ClusterMarkers_0_pval
  attr                        last_modified
 dset     GZIP   (4.991:1)   /row_attrs/Gene
  attr                        last_modified
 dset     GZIP   (118.888:1) /row_attrs/MotifRegulons
  attr                        last_modified
 dset     GZIP   (135.710:1) /row_attrs/TrackRegulons
  attr                        last_modified
 group                       /row_graphs


# Elapsed wall time: 2:07.16 = 127.16 seconds
$ h5repack -v -f GZIP=4 SCC_bbknn.SCENIC_SCope_output.loom SCC_bbknn.SCENIC_SCope_output.h5repack.gzip4.loom

No all objects to modify layout
All objects to apply filter are...
 All with GZIP, parameter 4
Making new file ...
-----------------------------------------
 Type     Filter (Compression)     Name
-----------------------------------------
 group                       /
  attr                        last_modified
 group                       /attrs
 dset       (1.000:1)        /attrs/CreationDate
 dset       (1.000:1)        /attrs/LOOM_SPEC_VERSION
 dset       (1.000:1)        /attrs/MetaData
 group                       /col_attrs
  attr                        last_modified
 dset     GZIP   (5.828:1)   /col_attrs/CellID
  attr                        last_modified
 dset     GZIP   (8.247:1)   /col_attrs/ClusterID
  attr                        last_modified
 dset     GZIP   (10.837:1)  /col_attrs/Clusterings
  attr                        last_modified
 dset     GZIP   (1.095:1)   /col_attrs/Embedding
  attr                        last_modified
 dset     GZIP   (1.075:1)   /col_attrs/Embeddings_X
  attr                        last_modified
 dset     GZIP   (1.082:1)   /col_attrs/Embeddings_Y
  attr                        last_modified
 dset     GZIP   (1.374:1)   /col_attrs/MotifRegulonsAUC
  attr                        last_modified
 dset     GZIP   (1.478:1)   /col_attrs/TrackRegulonsAUC
  attr                        last_modified
 dset     GZIP   (8.495:1)   /col_attrs/batch
  attr                        last_modified
 dset     GZIP   (8.493:1)   /col_attrs/louvain
  attr                        last_modified
 dset     GZIP   (1.485:1)   /col_attrs/n_counts
  attr                        last_modified
 dset     GZIP   (3.373:1)   /col_attrs/n_genes
  attr                        last_modified
 dset     GZIP   (1.148:1)   /col_attrs/percent_mito
  attr                        last_modified
 group                       /col_graphs
 group                       /layers
 dset     GZIP   (1.214:1)   /matrix
 group                       /row_attrs
  attr                        last_modified
 dset     GZIP   (87.771:1)  /row_attrs/ClusterMarkers_0
  attr                        last_modified
 dset     GZIP   (25.842:1)  /row_attrs/ClusterMarkers_0_avg_logFC
  attr                        last_modified
 dset     GZIP   (83.457:1)  /row_attrs/ClusterMarkers_0_pval
  attr                        last_modified
 dset     GZIP   (5.323:1)   /row_attrs/Gene
  attr                        last_modified
 dset     GZIP   (244.856:1) /row_attrs/MotifRegulons
  attr                        last_modified
 dset     GZIP   (312.184:1) /row_attrs/TrackRegulons
  attr                        last_modified
 group                       /row_graphs


# Filesize, filesize reduction ratio, time to compress.
SCC_bbknn.SCENIC_SCope_output.loom	373M
SCC_bbknn.SCENIC_SCope_output.gzip1.loom	251M	67.2922	2:02.01 = 122.01 seconds
SCC_bbknn.SCENIC_SCope_output.gzip2.loom	241M	64.6113	2:00.20 = 120.20 seconds
SCC_bbknn.SCENIC_SCope_output.gzip3.loom	232M	62.1984	2:05.18 = 125.18 seconds
SCC_bbknn.SCENIC_SCope_output.gzip4.loom	209M	56.0322	2:07.16 = 127.16 seconds
SCC_bbknn.SCENIC_SCope_output.gzip5.loom	202M	54.1555	2:18.66 = 138.66 seconds
SCC_bbknn.SCENIC_SCope_output.gzip6.loom	195M	52.2788	2:39.42 = 159.42 seconds
SCC_bbknn.SCENIC_SCope_output.gzip7.loom	194M	52.0107	3:04.44 = 184.44 seconds
SCC_bbknn.SCENIC_SCope_output.gzip8.loom	190M	50.9383	5:08.04 = 308.04 seconds
SCC_bbknn.SCENIC_SCope_output.gzip9.loom	187M	50.134	9:23.74 = 563.74 seconds
```

**Comment by ghuls** [comment]
One thing that might be nice to add a way to set the compression level.
To me it seems that compression level 4 seems to reduce the filesize quite a lot for not that much extra time compared with level 2.

```
Aerts_Fly_AdultBrain_Unfiltered_157k.loom	956M

# compression level, time
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip2.loom	585M	102.56169843673706
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip3.loom	561M	108.08579850196838
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip4.loom	462M	152.91423964500427
Aerts_Fly_AdultBrain_Unfiltered_157k.loompy.gzip8.loom	422M
```

**Comment by slinnarsson** [comment]
Looks good.

**Pull request merged**
